import Head from 'next/head'
import Hero from '../../components/learning-path/Hero'
import Layout from '../../components/layout/Layout'
import Second from '../../components/learning-path/Second'

const frontend = () => {
    return (
        <div>
            <Head>
                <title>Frontend Web Development Learning Path | Academire</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <div>
                <Layout>
                    <div className='flex-grow bg-gray-50'>
                        <Hero />
                        <Second />
                    </div>
                </Layout>
            </div>
        </div>
    )
}

export default frontend