import Head from 'next/head'
import Layout from '../components/layout/Layout'
import NavBar from '../components/learning-paths/NavBar'
import Course from '../components/courses/Course.jsx'

const Courses = () => {
  return (
    <div>
            <Head>
                <title>Learning Paths | Academire</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <div>
                <Layout>
                    <div className='flex'>
                        <NavBar />
                        <Course />
                    </div>
                </Layout>
            </div>
        </div>
  )
}

export default Courses