import Head from 'next/head'
import Explore from '../components/Home/Explore'
import Hero from '../components/Home/Hero'
import LearnAlone from '../components/Home/LearnAlone'
import Structure from '../components/Home/Structure'
import TutorialHell from '../components/Home/TutorialHell'
import Layout from '../components/layout/Layout'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Layout>
          <Hero />
          <TutorialHell />
          <Structure />
          <LearnAlone />
          <Explore />
        </Layout>
      </div>
    </div>
  )
}
