import Head from 'next/head'
import Layout from '../components/layout/Layout'
import Login from '../components/Login/Login'

const login = () => {
  return (
    <div>
      <Head>
        <title>Login | Academire</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        <Layout>
            <Login />
        </Layout>
      </div>
    </div>
  )
}

export default login