import Head from 'next/head'
import Layout from '../components/layout/Layout'
import Form from '../components/Register/Form'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Register | Academire</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        <Layout>
            <Form />
        </Layout>
      </div>
    </div>
  )
}