import Link from 'next/link'

const Terms = () => {
    return (
        <div className="relative" id="layout-conntainer">
            <div className="max-w-[85.5%] px-4 mx-auto py-[2rem]">
                <div id="terms-of-service-page" className="jsx-63b8c4223bd73cfd prose" style={{ maxWidth: "none" }}>
                    <h1 id="terms-and-conditions" className="text-[2.25em] font-extrabold mb-[0.8888889em] leading-[1.1111111]">Terms and Conditions</h1>
                    <p className="my-[1.25em] leading-[28px]">Welcome to academire. This page explains the terms by which you may use our online and/or mobile services, website, and software provided on or in connection with the service (collectively the &quot;Service&quot;). By accessing or using the Service, you signify that you have read, understood, and agree to be bound by this Terms of Service Agreement (“Agreement”) and to the collection and use of your information as set forth in the academire Privacy Policy , whether or not you are a registered user of our Service. This Agreement applies to all visitors, users, and others who access the Service (“Users”). PLEASE READ THIS AGREEMENT CAREFULLY TO ENSURE THAT YOU UNDERSTAND EACH PROVISION. THIS AGREEMENT CONTAINS A MANDATORY ARBITRATION OF DISPUTES PROVISION THAT REQUIRES THE USE OF ARBITRATION ON AN INDIVIDUAL BASIS TO RESOLVE DISPUTES, RATHER THAN JURY TRIALS OR CLASS ACTIONS.</p>
                    <h2  className="text-[24px] font-bold mb-[0.8888889em] leading-[1.1111111] uppercase" id="use-of-service">Use of Service</h2>
                    <p className="my-[1.25em] leading-[28px]">Academire provides an online interactive platform for taking and creating coding classes and video lectures.</p>
                    <h2  className="text-[24px] font-bold mb-[0.8888889em] leading-[1.1111111] uppercase" id="eligibility">1. Eligibility</h2>
                    <p className="my-[1.25em] leading-[28px]">This is a contract between you and academire. You must read and agree to these terms before using the academire Service. If you do not agree, you may not use the Service. You must be 16 years or older to use the Services. If you are less than 18 years of age and would like to register to use any part of the Services, please ask your parent or legal guardian to review and agree to these terms before you use any part of the Services, or ask them to complete the purchase or registration on your behalf. Supplemental terms and conditions may apply to some Services, such as rules for a particular competition, promotion, service or other activity, or terms that may accompany certain content accessible through the Services. Supplemental terms and conditions will be disclosed to you in connection with such competition, service or activity. Any supplemental terms and conditions are in addition to these terms and, in the event of a conflict, prevail over these terms. The Service is not available to any Users previously removed from the Service by academire.</p>
                    <h2  className="text-[24px] font-bold mb-[0.8888889em] leading-[1.1111111] uppercase" id="academire-service">2. academire Service</h2>
                    <p className="my-[1.25em] leading-[28px]">Subject to the terms and conditions of this Agreement, you are hereby granted a non-exclusive, limited, non-transferable, freely revocable license to use the Service for your personal, noncommercial use only and as permitted by the features of the Service. academire reserves all rights not expressly granted herein in the Service and the academire Content (as defined below). academire may terminate this license at any time for any reason or no reason.</p>
                    <h2  className="text-[24px] font-bold mb-[0.8888889em] leading-[1.1111111] uppercase" id="academire-accounts">3. academire Accounts</h2>
                    <p className="my-[1.25em] leading-[28px]">Your academire account gives you access to the services and functionality that we may establish and maintain from time to time and in our sole discretion. By connecting to academire with a third-party service (for example, Facebook or Google), you give us permission to access and use your information from that service as permitted by that service, and to store your log-in credentials for that service.</p>
                    <p className="my-[1.25em] leading-[28px]">You may never use another User&apos;s account without permission. When creating your account, you must provide accurate and complete information. You are solely responsible for the activity that occurs on your account, and you must keep your account password secure. We encourage you to use “strong” passwords (passwords that use a combination of upper and lower case letters, numbers and symbols) with your account. You must notify academire immediately of any breach of security or unauthorized use of your account. academire will not be liable for any losses caused by any unauthorized use of your account.</p>
                    <p className="my-[1.25em] leading-[28px]">You may control your User profile and how you interact with the Service by changing the settings in your settings page. By providing academire your email address you consent to our using the email address to send you Service-related notices, including any notices required by law, in lieu of communication by postal mail. We may also use your email address to send you other messages, such as changes to features of the Service and special offers. If you do not want to receive such email messages, you may opt out or change your preferences in your “settings” page. Opting out may prevent you from receiving email messages regarding updates, improvements, or offers.</p>
                    <h2  className="text-[24px] font-bold mb-[0.8888889em] leading-[1.1111111] uppercase" id="school-accounts">4. School Accounts</h2>
                    <p className="my-[1.25em] leading-[28px]">The Children&apos;s Online Privacy and Protection Act (“COPPA”) requires that online service providers obtain clear and verifiable parental consent before receiving personal information from children under 13. Because academire provides the Service to School to benefit and enhance the School&apos;s curriculum, academire RELIES ON SCHOOL TO OBTAIN AND PROVIDE APPROPRIATE CONSENT, IF NEEDED, TO COLLECT STUDENT INFORMATION. School represents and warrants that School has the authority to provide consent for academire to collect information from students before allowing students under 13 to access our Service, and that School has provided appropriate disclosures to students and parents regarding School&apos;s sharing of Student Data with service providers such as academire. We recommend that School provide a copy of our Privacy Policy to parents and guardians.</p>
                    <h2  className="text-[24px] font-bold mb-[0.8888889em] leading-[1.1111111] uppercase" id="service-rules">5. Service Rules</h2>
                    <p className="my-[1.25em] leading-[28px]">You agree not to engage in any of the following prohibited activities: (i) copying, distributing, or disclosing any part of the Service in any medium, including without limitation by any automated or non-automated “scraping”; (ii) using any automated system, including without limitation “robots,” “spiders,” “offline readers,” etc., to access the Service in a manner that sends more request messages to the academire servers than a human can reasonably produce in the same period of time by using a conventional on-line web browser (except that academire grants the operators of public search engines revocable permission to use spiders to copy materials from academire.com for the sole purpose of and solely to the extent necessary for creating publicly available searchable indices of the materials, but not caches or archives of such materials); (iii) transmitting spam, chain letters, or other unsolicited email; (iv) attempting to interfere with, compromise the system integrity or security or decipher any transmissions to or from the servers running the Service; (v) taking any action that imposes, or may impose at our sole discretion an unreasonable or disproportionately large load on our infrastructure; (vi) uploading invalid data, viruses, worms, or other software agents through the Service; (vii) collecting or harvesting any personally identifiable information, including account names, from the Service; (viii) using the Service for any commercial solicitation purposes; (ix) impersonating another person or otherwise misrepresenting your affiliation with a person or entity, conducting fraud, hiding or attempting to hide your identity; (x) interfering with the proper working of the Service; (xi) accessing any content on the Service through any technology or means other than those provided or authorized by the Service; or (xii) bypassing the measures we may use to prevent or restrict access to the Service, including without limitation features that prevent or restrict use or copying of any content or enforce limitations on use of the Service or the content therein.</p>
                    <p className="my-[1.25em] leading-[28px]">We may, without prior notice, change the Service; stop providing the Service or features of the Service, to you or to users generally; or create usage limits for the Service. We may permanently or temporarily terminate or suspend your access to the Service without notice and liability for any reason, including if in our sole determination you violate any provision of this Agreement, or for no reason. Upon termination for any reason or no reason, you continue to be bound by this Agreement.</p>
                    <p className="my-[1.25em] leading-[28px]">You are solely responsible for your interactions with other academire Users. We reserve the right, but have no obligation, to monitor disputes between you and other Users. academire shall have no liability for your interactions with other Users, or for any User&apos;s action or inaction.</p>
                    <h2  className="text-[24px] font-bold mb-[0.8888889em] leading-[1.1111111] uppercase" id="user-content">User Content</h2>
                    <p className="my-[1.25em] leading-[28px]">Some areas of the Service allow Users to post content such as profile information, comments, questions, course content and other content or information (any such materials a User submits, posts, displays, or otherwise makes available on the Service “User Content”). Access to these features may be subject to age restrictions. We claim no ownership rights over User Content created by you. The User Content you create remains yours; however, by sharing User Content through the Service, you agree to allow others to view, edit, and/or share your User Content in accordance with your settings and this Agreement. academire has the right (but not the obligation) in its sole discretion to remove any User Content that is shared via the Service.</p>
                    <p className="my-[1.25em] leading-[28px]">You agree not to post User Content that: (i) may create a risk of harm, loss, physical or mental injury, emotional distress, death, disability, disfigurement, or physical or mental illness to you, to any other person, or to any animal; (ii) may create a risk of any other loss or damage to any person or property; (iii) seeks to harm or exploit children by exposing them to inappropriate content, asking for personally identifiable details or otherwise; (iv) may constitute or contribute to a crime or tort; (v) contains any information or content that we deem to be unlawful, harmful, abusive, racially or ethnically offensive, defamatory, infringing, invasive of personal privacy or publicity rights, harassing, humiliating to other people (publicly or otherwise), libelous, threatening, profane, or otherwise objectionable; (vi) contains any information or content that is illegal (including, without limitation, the disclosure of insider information under securities law or of another party&apos;s trade secrets); (vii) contains any information or content that you do not have a right to make available under any law or under contractual or fiduciary relationships; or (viii) contains any information or content that you know is not correct and current or (ix) violates any school or other applicable policy, including those related to cheating or ethics. You agree that any User Content that you post does not and will not violate third-party rights of any kind, including without limitation any Intellectual Property Rights (as defined below) or rights of privacy. academire reserves the right, but is not obligated, to reject and/or remove any User Content that academire believes, in its sole discretion, violates these provisions. You understand that publishing your User Content on the Service is not a substitute for registering it with the U.S. Copyright Office, the Writer&apos;s Guild of America, or any other rights organization.</p>
                    <p className="my-[1.25em] leading-[28px]">For the purposes of this Agreement, “Intellectual Property Rights” means all patent rights, copyright rights, mask work rights, moral rights, rights of publicity, trademark, trade dress and service mark rights, goodwill, trade secret rights and other intellectual property rights as may now exist or hereafter come into existence, and all applications therefore and registrations, renewals and extensions thereof, under the laws of any state, country, territory or other jurisdiction.</p>
                    <p className="my-[1.25em] leading-[28px]">In connection with your User Content, you affirm, represent and warrant the following:</p>
                    <p className="my-[1.25em] leading-[28px]">Your User Content and academire&apos;s use thereof as contemplated by this Agreement and the Service will not violate any law or infringe any rights of any third party, including but not limited to any Intellectual Property Rights and privacy rights. academire may exercise the rights to your User Content granted under this Agreement without liability for payment of any guild fees, residuals, payments, fees, or royalties payable under any collective bargaining agreement or otherwise. To the best of your knowledge, all your User Content you provide to us is truthful and accurate. You have the written consent of each and every identifiable natural person in the User Content, if any, to use such person&apos;s name or likeness in the manner contemplated by the Service and this Agreement, and each such person has released you from any liability that may arise in relation to such use. academire takes no responsibility and assumes no liability for any User Content that you or any other User or third party posts or sends over the Service. You shall be solely responsible for your User Content and the consequences of posting or publishing it, and you agree that we are only acting as a passive conduit for your online distribution and publication of your User Content. You understand and agree that you may be exposed to User Content that is inaccurate, objectionable, inappropriate for children, or otherwise unsuited to your purpose, and you agree that academire shall not be liable for any damages you allege to incur as a result of User Content.</p>
                    <h2  className="text-[24px] font-bold mb-[0.8888889em] leading-[1.1111111] uppercase" id="user-content-license-grant">User Content License Grant</h2>
                    <p className="my-[1.25em] leading-[28px]">By posting any User Content on the Service, you expressly grant, and you represent and warrant that you have all rights necessary to grant, to academire a royalty-free, sublicensable, transferable, perpetual, irrevocable, non-exclusive, worldwide license to use, reproduce, modify, publish, list information regarding, edit, translate, distribute, syndicate, publicly perform, publicly display, and make derivative works of all such User Content and your name, voice, and/or likeness as contained in your User Content, in whole or in part, and in any form, media or technology, whether now known or hereafter developed, for use in connection with the Service and academire&apos;s (and its successors&apos; and affiliates&apos;) business, including without limitation for promoting and redistributing part or all of the Service (and derivative works thereof) in any media formats and through any media channels. You also hereby grant each User of the Service a non-exclusive license to access your User Content through the Service, and to use, display, reproduce and perform such User Content solely as permitted through the functionality of the Service and under this Agreement.</p>
                    <h2  className="text-[24px] font-bold mb-[0.8888889em] leading-[1.1111111] uppercase" id="mobile-software">Mobile Software</h2>
                    <h3  className='text-[20px] leading-[32px] font-semibold'>1. Mobile Software</h3>
                    <p className="my-[1.25em] leading-[28px]">We may make available software to access the Service via a mobile device (“Mobile Software”). To use the Mobile Software you must have a mobile device that is compatible with the Mobile Service. academire does not warrant that the Mobile Software will be compatible with your mobile device. academire hereby grants you a non-exclusive, non-transferable, revocable license to use a compiled code copy of the Mobile Software for one academire account on one mobile device owned or leased solely by you, for your personal use. You may not: (i) modify, disassemble, decompile or reverse engineer the Mobile Software, except to the extent that such restriction is expressly prohibited by law; (ii) rent, lease, loan, resell, sublicense, distribute or otherwise transfer the Mobile Software to any third party or use the Mobile Software to provide time sharing or similar services for any third party; (iii) make any copies of the Mobile Software; (iv) remove, circumvent, disable, damage or otherwise interfere with security-related features of the Mobile Software, features that prevent or restrict use or copying of any content accessible through the Mobile Software, or features that enforce limitations on use of the Mobile Software; or (v) delete the copyright and other proprietary rights notices on the Mobile Software. You acknowledge that academire may from time to time issue upgraded versions of the Mobile Software, and may automatically electronically upgrade the version of the Mobile Software that you are using on your mobile device. You consent to such automatic upgrading on your mobile device, and agree that the terms and conditions of this Agreement will apply to all such upgrades. Any third-party code that may be incorporated in the Mobile Software is covered by the applicable open source or third-party license EULA, if any, authorizing use of such code. The foregoing license grant is not a sale of the Mobile Software or any copy thereof, and academire or its third party partners or suppliers retain all right, title, and interest in the Mobile Software (and any copy thereof). Any attempt by you to transfer any of the rights, duties or obligations hereunder, except as expressly provided for in this Agreement, is void. academire reserves all rights not expressly granted under this Agreement. You agree to comply with all Pakistan and foreign laws related to use of the Mobile Software and the academire Service.</p>
                    <h2  className="text-[24px] font-bold mb-[0.8888889em] leading-[1.1111111] uppercase" id="mobile-software-app-store">2. Mobile Software from App Store</h2>
                    <p className="my-[1.25em] leading-[28px]">The following applies to any Mobile Software you acquire from the App Store (“iTunes-Sourced Software”): You acknowledge and agree that this Agreement is solely between you and academire, not Apple, and that Apple has no responsibility for the iTunes-Sourced Software or content thereof. Your use of the iTunes-Sourced Software must comply with the App Store Terms of Service. You acknowledge that Apple has no obligation whatsoever to furnish any maintenance and support services with respect to the iTunes-Sourced Software. In the event of any failure of the iTunes-Sourced Software to conform to any applicable warranty, you may notify Apple, and Apple will refund the purchase price for the iTunes-Sourced Software to you; to the maximum extent permitted by applicable law, Apple will have no other warranty obligation whatsoever with respect to the iTunes-Sourced Software, and any other claims, losses, liabilities, damages, costs or expenses attributable to any failure to conform to any warranty will be solely governed by this Agreement and any law applicable to academire as provider of the software. You acknowledge that Apple is not responsible for addressing any claims of you or any third party relating to the iTunes-Sourced Software or your possession and/or use of the iTunes-Sourced Software, including, but not limited to: (i) product liability claims; (ii) any claim that the iTunes-Sourced Software fails to conform to any applicable legal or regulatory requirement; and (iii) claims arising under consumer protection or similar legislation; and all such claims are governed solely by this Agreement and any law applicable to academire as provider of the software. You acknowledge that, in the event of any third party claim that the iTunes-Sourced Software or your possession and use of that iTunes-Sourced Software infringes that third party&apos;s intellectual property rights, academire, not Apple, will be solely responsible for the investigation, defense, settlement and discharge of any such intellectual property infringement claim to the extent required by this Agreement. You and academire acknowledge and agree that Apple, and Apple&apos;s subsidiaries, are third party beneficiaries of this Agreement as relates to your license of the iTunes-Sourced Software, and that, upon your acceptance of the terms and conditions of this Agreement, Apple will have the right (and will be deemed to have accepted the right) to enforce this Agreement as relates to your license of the iTunes-Sourced Software against you as a third party beneficiary thereof.</p>
                    <h2  className="text-[24px] font-bold mb-[0.8888889em] leading-[1.1111111] uppercase" id="proprietary-rights">Our Proprietary Rights</h2>
                    <p className="my-[1.25em] leading-[28px]">Except for your User Content, the Service and all materials therein or transferred thereby, including, without limitation, software, images, text, graphics, illustrations, logos, patents, trademarks, service marks, copyrights, photographs, audio, videos, music, and User Content belonging to other Users (the “academire Content”), and all Intellectual Property Rights related thereto, are the exclusive property of academire and its licensors (including other Users who post User Content to the Service). Except as explicitly provided herein, nothing in this Agreement shall be deemed to create a license in or under any such Intellectual Property Rights, and you agree not to sell, license, rent, modify, distribute, copy, reproduce, transmit, publicly display, publicly perform, publish, adapt, edit or create derivative works from any academire Content. Use of the academire Content for any purpose not expressly permitted by this Agreement is strictly prohibited.</p>
                    <p className="my-[1.25em] leading-[28px]">You may choose to or we may invite you to submit comments or ideas about the Service, including without limitation about how to improve the Service or our products (“Ideas”). By submitting any Idea, you agree that your disclosure is gratuitous, unsolicited and without restriction and will not place academire under any fiduciary or other obligation, and that we are free to use the Idea without any additional compensation to you, and/or to disclose the Idea on a non-confidential basis or otherwise to anyone. You further acknowledge that, by acceptance of your submission, academire does not waive any rights to use similar or related ideas previously known to academire, or developed by its employees, or obtained from sources other than you.</p>
                    <h2  className="text-[24px] font-bold mb-[0.8888889em] leading-[1.1111111] uppercase" id="reputational-data">academire Reputational Data</h2>
                    <p className="my-[1.25em] leading-[28px]">Certain aspects of the Service may allow you to obtain certain reputational or status indicators (for example, score and points for completing courses and labs) (“academire Indicators”). You understand and agree that regardless of terminology used, “academire Indicators represent a limited license right governed solely by the terms of this Agreement and available for distribution at “academire&apos;s sole discretion. “academire Indicators are not redeemable for any sum of money or monetary value from “academire at any time. You acknowledge that you do not own the account you use to access the Service, nor do you possess any rights of access or rights to data stored by or on behalf of “academire on “academire servers, including without limitation any data representing or embodying any or all of your “academire Indicators. You agree that “academire has the absolute right to manage, regulate, control, modify and/or eliminate “academire Indicators as it sees fit in its sole discretion, in any general or specific case, and that “academire will have no liability to you based on its exercise of such right. All data on “academire&apos;s servers are subject to deletion, alteration or transfer. NOTWITHSTANDING ANY VALUE ATTRIBUTED TO SUCH DATA BY YOU OR ANY THIRD PARTY, YOU UNDERSTAND AND AGREE THAT ANY DATA, ACCOUNT HISTORY AND ACCOUNT CONTENT RESIDING ON “academire&apos;s SERVERS, MAY BE DELETED, ALTERED, MOVED OR TRANSFERRED AT ANY TIME FOR ANY REASON IN “academire&apos;S SOLE DISCRETION, WITH OR WITHOUT NOTICE AND WITH NO LIABILITY OF ANY KIND. “academire DOES NOT PROVIDE OR GUARANTEE, AND EXPRESSLY DISCLAIMS, ANY VALUE, CASH OR OTHERWISE, ATTRIBUTED TO ANY DATA RESIDING ON “ACADEMIRE&apos;S SERVERS.</p>
                    <h2  className="text-[24px] font-bold mb-[0.8888889em] leading-[1.1111111] uppercase" id="referral-system">Referral System</h2>
                    <p className="my-[1.25em] leading-[28px]">The prizes mentioned in the referral system provided by academire is only applicable for Pakistan accounts at the moment. academire may add new countries or remove existing countries at any time in its sole discretion. Any account found abusing referral system through bots, automated scripts, or other spam means is in violation of the terms.</p>
                    <h2  className="text-[24px] font-bold mb-[0.8888889em] leading-[1.1111111] uppercase" id="hackfest-event">HackFest Event</h2>
                    <p className="my-[1.25em] leading-[28px]">The physical goods/prizes mentioned in the HackFest event provided by academire is only applicable for countries where Amazon supports deliveries. academire may add new countries or remove existing countries at any time in its sole discretion. Any account found abusing HackFest through bots, automated scripts, or other spam means is in violation of the terms. The decision of the judges to evaluate your project idea is final and binding. academire team at its sole discretion may decide to qualify or disqualify your project at any time without any prior notice.</p>
                    <p className="my-[1.25em] leading-[28px]">The monetary compensation in the referral system provided by academire shall be executed if and only if the referred Pro member a) renews their subscription for the next billing cycle, OR b) their subscription amount corresponds to $20 or more in value.</p>
                    <h2  className="text-[24px] font-bold mb-[0.8888889em] leading-[1.1111111] uppercase" id="paid-services">Paid Services</h2>
                    <h3 className='text-[20px] leading-[32px] font-semibold'>1. Billing Policies</h3>
                    <p className="my-[1.25em] leading-[28px]">Certain aspects of the Service may be provided for a fee or other charge. If you elect to use paid aspects of the Service, you agree to the pricing and payment terms, as we may update them from time to time. academire may add new services for additional fees and charges, or amend fees and charges for existing services, at any time in its sole discretion. Any change to our pricing or payment terms shall become effective in the billing cycle following notice of such change to you as provided in this Agreement or otherwise.</p>
                    <h3  className='text-[20px] leading-[32px] font-semibold'>2. Automatic Renewal</h3>
                    <p className="my-[1.25em] leading-[28px]">academire subscriptions renew automatically using the payment details on file for your account. If you purchase a subscription with automatic renewal, you acknowledge and agree that we are authorized to use the payment information on file for the renewal fee. Until you cancel, your subscription will renew monthly, 3-monthly, half-yearly or annually on the same day of the month or year, respectively, as the date you made your initial purchase and the payment information on file will be billed for the then-current subscription fee. This purchase date will be included on your subscription confirmation receipt that will be emailed to you at the email you provide. You may cancel your Pro account at any time from within the Settings section of your Account Settings. This will stop future subscription charges from accruing to your account.</p>
                    <h3  className='text-[20px] leading-[32px] font-semibold'>3. No Refunds</h3>
                    <p className="my-[1.25em] leading-[28px]">You may cancel your academire account at any time; however, there are no partial or pro-rata refunds for cancellation except for the first 7 days from the first subscription date. If you cancel your subscription, cancellation will be effective immediately and you lose access to academire Pro material. academire may offer partial, pro rata refunds for academire&apos;s early suspension, termination, or cancellation of a paid program, where the pricing and payment terms for the specific academire program expressly state that such refunds are available in such scenarios and/or as required by law. In the event that you cancel your account or academire suspends or terminates your account under this Agreement for your breach of this Agreement, you understand and agree that you shall receive no refund or exchange for any academire Indicators, any unused time on a subscription, any license or subscription fees for any portion of the Service, any content or data associated with your account, or for anything else.</p>
                    <h3  className='text-[20px] leading-[32px] font-semibold'>4. Free Trials</h3>
                    <p className="my-[1.25em] leading-[28px]">academire may offer a free trial of our Service to new and eligible returning subscribers, subject to specific terms explained during your free trial sign-up. To avoid being charged during a free trial promotion, you must cancel your subscription before your free trial ends. You can view the details of your free trial on your academire Account Settings page. academire reserves the right to determine eligibility for free trials, which may vary based on factors including the subscription selected and how recently you redeemed a free trial. Certain limitations may also exist with respect to combining free trials with any other offers. If you do not cancel prior to the end of your free trial period, the payment method provided at sign-up will be automatically billed for the applicable subscription fee. If you wish to avoid charges to the payment information that you have on file, you must cancel your subscription prior to the end of the seven (7) day period beginning at the time that you began your free trial. You may cancel your subscription at any time as described in the “Cancellations” section of these Terms.</p>
                    <h3  className='text-[20px] leading-[32px] font-semibold'>5. Cancellations</h3>
                    <p className="my-[1.25em] leading-[28px]">You can cancel your subscription at any time by logging into your academire account on the academire site and following the instructions on the Account Settings page. You must cancel your subscription prior to your next recurring billing date in order to avoid being charged. If you cancel your subscription, you will continue to have access to the Service through the end of your current billing period, but will not receive a refund. Cancelling your subscription will not completely delete your account from our Service. You may choose to delete your account, but you will not be able to recover data from your former account at a later date if you do so.</p>
                    <h3  className='text-[20px] leading-[32px] font-semibold'>6. Payment Information; Taxes</h3>
                    <p className="my-[1.25em] leading-[28px]">All information that you provide in connection with a purchase or transaction or other monetary transaction interaction with the Service must be accurate, complete, and current. You agree to pay all charges incurred by users of your credit card, debit card, or other payment method used in connection with a purchase or transaction or other monetary transaction interaction with the Service at the prices in effect when such charges are incurred. You will pay any applicable taxes relating to any such purchases, transactions or other monetary transaction interactions.</p>
                    <h2  className="text-[24px] font-bold mb-[0.8888889em] leading-[1.1111111] uppercase" id="privacy">Privacy</h2>
                    <p className="my-[1.25em] leading-[28px]">We care about the privacy of our Users. You understand that by using the Services you consent to the collection, use and disclosure of your personally identifiable information and aggregate data as set forth in our <Link href="/privacy-policy"><a className="black-color underline-offset-2 font-medium decoration-2 new-color">Privacy Policy</a></Link>, and to have your personally identifiable information collected, used, transferred to and processed in Pakistan.</p>
                    <h2  className="text-[24px] font-bold mb-[0.8888889em] leading-[1.1111111] uppercase" id="security">Security</h2>
                    <p className="my-[1.25em] leading-[28px]">academire cares about the integrity and security of your personal information. However, we cannot guarantee that unauthorized third parties will never be able to defeat our security measures or use your personal information for improper purposes. You acknowledge that you provide your personal information at your own risk.</p>
                    <h2  className="text-[24px] font-bold mb-[0.8888889em] leading-[1.1111111] uppercase" id="third-party-links">Third-Party Links</h2>
                    <p className="my-[1.25em] leading-[28px]">The Service may contain links to third-party websites, advertisers, services, special offers, or other events or activities that are not owned or controlled by academire. academire does not endorse or assume any responsibility for any such third-party sites, information, materials, products, or services. If you access a third party website from the Service, you do so at your own risk, and you understand that this Agreement and academire&apos;s Privacy Policy do not apply to your use of such sites. You expressly relieve academire from any and all liability arising from your use of any third-party website, service, or content. Additionally, your dealings with or participation in promotions of advertisers found on the Service, including payment and delivery of goods, and any other terms (such as warranties) are solely between you and such advertisers. You agree that academire shall not be responsible for any loss or damage of any sort relating to your dealings with such advertisers.</p>
                    <h2  className="text-[24px] font-bold mb-[0.8888889em] leading-[1.1111111] uppercase" id="indemnity">Indemnity</h2>
                    <p className="my-[1.25em] leading-[28px]">You agree to defend, indemnify and hold harmless academire and its subsidiaries, agents, licensors, managers, and other affiliated companies, and their employees, contractors, agents, officers and directors, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney&apos;s fees) arising out of or related to: (i) your use of and access to the Service, including any data or content transmitted or received by you; (ii) your violation of any term of this Agreement, including without limitation your breach of any of the representations and warranties above; (iii) your violation of any third-party right, including without limitation any right of privacy or Intellectual Property Rights; (iv) your violation of any applicable law, rule or regulation; (v) User Content or any other information or content that is submitted via your account including without limitation misleading, false or inaccurate information; (vi) negligent or willful misconduct; or (vii) any other party&apos;s access and use of other appropriate security code.</p>
                    <h2  className="text-[24px] font-bold mb-[0.8888889em] leading-[1.1111111] uppercase" id="no-warranty">No Warranty</h2>
                    <p className="my-[1.25em] leading-[28px] uppercase">THE SERVICE IS PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS. USE OF THE SERVICE IS AT YOUR OWN RISK. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE SERVICE IS PROVIDED WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. WITHOUT LIMITING THE FOREGOING, academire, ITS SUBSIDIARIES, ITS AFFILIATES, AND ITS LICENSORS DO NOT WARRANT THAT THE CONTENT IS ACCURATE, RELIABLE OR CORRECT; THAT THE SERVICE WILL MEET YOUR REQUIREMENTS; THAT THE SERVICE WILL BE AVAILABLE AT ANY PARTICULAR TIME OR LOCATION, UNINTERRUPTED OR SECURE; THAT ANY DEFECTS OR ERRORS WILL BE CORRECTED; OR THAT THE SERVICE IS FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. ANY CONTENT DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SERVICE IS DOWNLOADED AT YOUR OWN RISK AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR MOBILE DEVICE OR LOSS OF DATA THAT RESULTS FROM SUCH DOWNLOAD OR YOUR USE OF THE SERVICE.</p>
                    <p className="my-[1.25em] leading-[28px] uppercase">SOME STATES DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, SO THE ABOVE EXCLUSIONS MAY NOT APPLY TO YOU. THIS AGREEMENT GIVES YOU SPECIFIC LEGAL RIGHTS, AND YOU MAY ALSO HAVE OTHER RIGHTS WHICH VARY FROM STATE TO STATE. THE DISCLAIMERS AND EXCLUSIONS UNDER THIS AGREEMENT WILL NOT APPLY TO THE EXTENT PROHIBITED BY APPLICABLE LAW.</p>
                    <p className="my-[1.25em] leading-[28px] uppercase">academire DOES NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR ANY PRODUCT OR SERVICE ADVERTISED OR OFFERED BY A THIRD PARTY THROUGH THE academire SERVICE OR ANY HYPERLINKED WEBSITE OR SERVICE, AND academire WILL NOT BE A PARTY TO OR IN ANY WAY MONITOR ANY TRANSACTION BETWEEN YOU AND THIRD-PARTY PROVIDERS OF PRODUCTS OR SERVICES.</p>
                    <h2 className="text-[24px] font-bold mb-[0.8888889em] leading-[1.1111111] uppercase">Limitation of Liability</h2>
                    <p className="my-[1.25em] leading-[28px] uppercase">TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL academire, ITS AFFILIATES, AGENTS, DIRECTORS, EMPLOYEES, SUPPLIERS OR LICENSORS BE LIABLE FOR ANY INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING WITHOUT LIMITATION DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES, ARISING OUT OF OR RELATING TO THE USE OF, OR INABILITY TO USE, THIS SERVICE. UNDER NO CIRCUMSTANCES WILL academire BE RESPONSIBLE FOR ANY DAMAGE, LOSS OR INJURY RESULTING FROM HACKING, TAMPERING OR OTHER UNAUTHORIZED ACCESS OR USE OF THE SERVICE OR YOUR ACCOUNT OR THE INFORMATION CONTAINED THEREIN.</p>
                    <p className="my-[1.25em] leading-[28px] uppercase">TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, ACADEMIRE ASSUMES NO LIABILITY OR RESPONSIBILITY FOR ANY (I) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT; (II) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO OR USE OF OUR SERVICE; (III) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION STORED THEREIN; (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE SERVICE; (V) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE THAT MAY BE TRANSMITTED TO OR THROUGH OUR SERVICE BY ANY THIRD PARTY; (VI) ANY ERRORS OR OMISSIONS IN ANY CONTENT OR FOR ANY LOSS OR DAMAGE INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE THROUGH THE SERVICE; AND/OR (VII) USER CONTENT OR THE DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY THIRD PARTY. IN NO EVENT SHALL academire, ITS AFFILIATES, AGENTS, DIRECTORS, EMPLOYEES, SUPPLIERS, OR LICENSORS BE LIABLE TO YOU FOR ANY CLAIMS, PROCEEDINGS, LIABILITIES, OBLIGATIONS, DAMAGES, LOSSES OR COSTS IN AN AMOUNT EXCEEDING THE AMOUNT YOU PAID TO ACADEMIRE HEREUNDER OR RS1000.00, WHICHEVER IS GREATER.</p>
                    <p className="my-[1.25em] leading-[28px] uppercase">THIS LIMITATION OF LIABILITY SECTION APPLIES WHETHER THE ALLEGED LIABILITY IS BASED ON CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY, OR ANY OTHER BASIS, EVEN IF ACADEMIRE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. THE FOREGOING LIMITATION OF LIABILITY SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW IN THE APPLICABLE JURISDICTION.</p>
                    <p className="my-[1.25em] leading-[28px] uppercase">SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATIONS OR EXCLUSIONS MAY NOT APPLY TO YOU. THIS AGREEMENT GIVES YOU SPECIFIC LEGAL RIGHTS, AND YOU MAY ALSO HAVE OTHER RIGHTS WHICH VARY FROM STATE TO STATE. THE EXCLUSIONS AND LIMITATIONS OF LIABILITY UNDER THIS AGREEMENT WILL NOT APPLY TO THE EXTENT PROHIBITED BY APPLICABLE LAW.</p>
                    <p className="my-[1.25em] leading-[28px] uppercase">The Service is controlled and operated from facilities in Pakistan. academire makes no representations that the Service is appropriate or available for use in other locations. Those who access or use the Service from other jurisdictions do so at their own volition and are entirely responsible for compliance with all applicable Pakistan and local laws and regulations, including but not limited to export and import regulations. You may not use the Service if you are a resident of a country embargoed by Pakistan, or are a foreign person or entity blocked or denied by the Pakistan government. Unless otherwise explicitly stated, all materials found on the Service are solely directed to individuals, companies, or other entities located in Pakistan</p>
                    <h2  className="text-[24px] font-bold mb-[0.8888889em] leading-[1.1111111] uppercase" id="contact">Contact</h2>
                    <p className="my-[1.25em] leading-[28px]">For legal notices please e-mail or serve us at support@academire.com. You can also contact us via our &quot;Contact Us&quot; link above.</p>
                    <p className="my-[1.25em] leading-[28px]">This Agreement was last modified on May 29th, 2022.</p>
                </div>
            </div>
        </div>
    )
}

export default Terms